### ISSUE TITLE
Kerberos tests are failing on JDK11

### ISSUE THREAD

**Issue by eolivelli** [diennea/blazingcache#150]
This is the error, see the same on https://github.com/diennea/herddb for the fix, the test case is mostrly a cut-and-paste

java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at blazingcache.client.JAASKerberosTest.basicTest(JAASKerberosTest.java:164)

**Comment by eolivelli** [comment]
Not an issue, CI was not building current master...
