### ISSUE TITLE
Speed up messageId generation

### ISSUE THREAD

**Issue by dmercuriali** [diennea/blazingcache#174]
In production we are observing a lot of threads spending time on the messageId UUID generation.

`"pool-1-thread-352" #5075 prio=5 os_prio=0 cpu=0.57ms elapsed=171.24s tid=0x00007f428478c250 nid=0x3cb917 runnable  [0x00007f42231ec000]
   java.lang.Thread.State: RUNNABLE
        at java.util.Arrays.copyOfRange(java.base@17.0.3/Arrays.java:3822)
        at sun.security.provider.NativePRNG$RandomIO.implNextBytes(java.base@17.0.3/NativePRNG.java:556)
        - locked <0x0000000201364158> (a java.lang.Object)
        at sun.security.provider.NativePRNG.engineNextBytes(java.base@17.0.3/NativePRNG.java:221)
        at java.security.SecureRandom.nextBytes(java.base@17.0.3/SecureRandom.java:758)
        at java.util.UUID.randomUUID(java.base@17.0.3/UUID.java:151)
        at blazingcache.network.netty.NettyChannel.sendReplyMessage(NettyChannel.java:131)
        at blazingcache.client.CacheClient.messageReceived(CacheClient.java:835)
        at blazingcache.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:81)
        at blazingcache.network.netty.NettyChannel$$Lambda$711/0x0000000801840f38.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.3/Executors.java:539)
        at java.util.concurrent.FutureTask.run(java.base@17.0.3/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.3/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.3/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)`

We could look for a way to speed up the generation of the UUID

**Comment by eolivelli** [comment]
probably you have some problems with the PRNG ?
usually UUID.randomUUID is really fast, maybe on those machines you would also see problems with TLS.

btw, do you really need a globally unique ID ?
or is it enough to build a ID with a incremental number generated by the client ?
the ID is used for request/reply, IIRC

you can replace that with a AtomicLong generated by the NettyChannel
does it make sense ?

**Comment by dmercuriali** [comment]
Yes the ID is used for requests and replies, it should be unique for the (usually) small timespan in which we are waiting for the reply, after that it can be used for another request.
I've run some benchmarks and forcing the UUID generation to use a SecureRandom with the SHA1PRNG algorithms speeds things up, but to do that we need to add a dependency to https://github.com/cowtowncoder/java-uuid-generator 

The AtomicLong would be faster for sure. We could still cast it to String to avoid making changes to a lot of things. I don't think it will ever overflow, and even if it does it won't be a problem
